### PR TITLE
Hacky rewrite of the plugin to fix issues with output directory and embedding

### PR DESCRIPTION
**Pull request by JanX2**
Please review and change anything that doesn’t feel right or not Pythonic. I’m not at all experienced in writing Python. Assume I hav no idea what I’m doing. Though, at least currently, my rewrite works for me. 

Thank you for handing me a solid foundation!

### CODE REVIEW

**Comment by bindestriche** [comment]
I am glad this is usefull to someone. I will look at it as soon as I can find the time (in 3 weeks the earliest)

**Comment by JanX2** [comment]
@bindestriche 
Thanks! I’m glad you are interested. :)

**Comment by JanX2** [comment]
@bindestriche 
Any news regarding my approach?

**Comment by bindestriche** [comment]
>  Any news regarding my approach?
I just merged it hoping for the best.

**Pull request merged**
